#!/usr/bin/env bash
# configures the nginx server so that /redirect_me is redirecting to https://www.google.com

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
