#!/usr/bin/env bash
# prints the current running processes

sudo bash -c "echo $$ > /var/run/myscript.pid"
trap "rm -r /var/run/myscript.pid; echo I hate the kill command;exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -r /var/run/myscript.pid; exit" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
